//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.10.21 at 01:24:30 AM EEST
//


package ua.nure.danylenko.practice7.entity;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Type complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="Type">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="peripheral" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="port" type="{http://nure.ua/danylenko/practice7}Port" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="power" type="{http://nure.ua/danylenko/practice7}Watts" minOccurs="0"/>
 *         &lt;element name="cooler" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="group" type="{http://nure.ua/danylenko/practice7}group" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Type", propOrder = {
        "peripheral",
        "port",
        "power",
        "cooler",
        "group"
})
public class Type {

    protected Boolean peripheral;
    @XmlSchemaType(name = "string")
    protected List<Port> port;
    protected Integer power;
    protected Boolean cooler;
    @XmlSchemaType(name = "string")
    protected Group group;

    /**
     * Gets the value of the peripheral property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isPeripheral() {
        return peripheral;
    }

    /**
     * Sets the value of the peripheral property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setPeripheral(Boolean value) {
        this.peripheral = value;
    }

    /**
     * Gets the value of the port property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the port property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPort().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Port }
     *
     *
     */
    public List<Port> getPort() {
        if (port == null) {
            port = new ArrayList<Port>();
        }
        return this.port;
    }

    /**
     * Gets the value of the power property.
     *
     * @return
     *     possible object is
     *     {@link Integer }
     *
     */
    public Integer getPower() {
        return power;
    }

    /**
     * Sets the value of the power property.
     *
     * @param value
     *     allowed object is
     *     {@link Integer }
     *
     */
    public void setPower(Integer value) {
        this.power = value;
    }

    /**
     * Gets the value of the cooler property.
     *
     * @return
     *     possible object is
     *     {@link Boolean }
     *
     */
    public Boolean isCooler() {
        return cooler;
    }

    /**
     * Sets the value of the cooler property.
     *
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *
     */
    public void setCooler(Boolean value) {
        this.cooler = value;
    }

    /**
     * Gets the value of the group property.
     *
     * @return
     *     possible object is
     *     {@link Group }
     *
     */
    public Group getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     *
     * @param value
     *     allowed object is
     *     {@link Group }
     *
     */
    public void setGroup(Group value) {
        this.group = value;
    }

}
